article/urls.py
from django.conf.urls import url

from . import views

app_name = 'article'
urlpatterns = [
    #article/
    url(r'^$', views.article, name='article'),
    #article/categorie/[0-9]*
    url(r'^categorie/(?P<cat_id>[0-9]+)/', views.categorie, name="categorie"),
    #article/categorie/
    url(r'^categorie/', views.all_categorie, name="categorie_all"),
    #article/create_categorie/
    url(r'^create_categorie/', views.create_categorie, name="create_cat"),
    #article/edit/[0-9]*
    url(r'^edit/(?P<id_art>[0-9]*)/', views.edit, name="edit"),
    #article/edit/
    url(r'edit/', views.article),
    #article/edit/
    url(r'^create/', views.create, name="create"),
    #article/user_article/[0-9]*
    url(r'^user_article/(?P<user_id>[0-9]+)/', views.user_article, name="user_art"),
    #article/user_article/
    url(r'^user_article/', views.article),
    #article/read/[0-9]*/
    url(r'^read/(?P<art_id>[0-9]+)/', views.read, name='read'),
    #article/read/
    url(r'^read/', views.article)
]

index/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'index'
urlpatterns = [
    #index/
    url(r'^$', views.index, name='index'),
    #index/login/
    url(r'^login/$', auth_views.login, {'template_name': 'index/login.html'}, name="login"),
    #index/logout/
    url(r'^logout/$', auth_views.logout, {'next_page': '/index/'}, name="logout"),
    #index/register/
    url(r'^register/', views.create_user, name="registration"),
    #index/search/[A-Za-z0-9]*
    url(r'^search/', views.search, name="search"),
]

sciMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from index.views import index as art_index

urlpatterns = [
    url(r'^$', art_index),
    url(r'^index/', include('index.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^admin/', admin.site.urls),
]

article/models.py
from django.db import models
import datetime

class Categories(models.Model):
    id  = models.AutoField(primary_key=True)
    cat = models.CharField(max_length=50)

class Articles(models.Model):
    id         = models.AutoField(primary_key=True)
    title      = models.CharField(max_length=50)
    author     = models.CharField(max_length=50)
    add_date   = models.DateField('add_date', default=datetime.date.today)
    date_pub   = models.DateField('date published')
    categories = models.ForeignKey('categories', on_delete=models.CASCADE)
    abstract   = models.CharField(max_length=1000)
    keyword    = models.CharField(max_length=1000)
    content    = models.CharField(max_length=100000)
    ref        = models.CharField(max_length=1000)
    writer     = models.IntegerField(default=0)

article/forms.py
from django import forms
from datetime import datetime

from .models import Categories

#formulaire de creation d'article
class create_article(forms.Form):
    titre = forms.CharField(label="titre",
                widget=forms.TextInput(attrs={'class': 'form-control'}))
    auteur = forms.CharField(label="Auteur",
                widget=forms.TextInput(attrs={'class': 'form-control'}))
    date = forms.DateField(label="date",
                widget=forms.DateInput(attrs={'class': 'form-control'})) 
    
    tmp = Categories.objects.all()
    cat = []
    for c in tmp :
        cat.append((c.id, c.cat))

    categories = forms.ChoiceField(label="categories", 
                                   choices=cat,
                widget=forms.Select(attrs={'class': 'form-control'}))
    reference = forms.CharField(label="reference",
                widget=forms.Textarea(attrs={'class': 'form-control',
                    }))
    hidden_content=forms.CharField(widget=forms.HiddenInput(attrs={'id': 'hidden_content'}))

#formulaire de creation de categorie
class create_cat(forms.Form):
    categorie = forms.CharField(label="categorie",
                widget=forms.TextInput(attrs={'class': 'form-control'}))

article/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.messages import error

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect

import datetime

from .models import Categories, Articles
from .forms import create_article, create_cat

# Create your views here.
def article(request):
    cat = Categories.objects.all()[:5]
    art = Articles.objects.all()
    return render(request, "article/index.html", {'l_art': art, 'cat': cat})

def categorie(request, cat_id):
    cat = Categories.objects.all()[:5]
    art = Articles.objects.filter(categories_id=cat_id)
    cat_name = Categories.objects.get(id=cat_id)

    return render(request, "article/article_list.html", {'cat': cat,
                                                         'l_art': art, 
                                                         'cat_name': cat_name
                                                        })

def all_categorie(request):
    try :
        cat_l = Categories.objects.all()
    except Categories.DoesNotExist :
        cat_l = {'content': 'pas de categories repertoriees'}    
    cat = cat_l[:5]
    
    return render(request, "article/categorie_list.html", {'cat': cat, 'l_cat': cat_l})

@staff_member_required(login_url='index:login')
def create_categorie(request) :
    cat = Categories.objects.all()[:5]

    if request.method == "POST":
        form = create_cat(request.POST)
        if form.is_valid():
            cat_name = form.cleaned_data['categorie']

            cat = Categories(cat=cat_name)
            cat.save()

            return HttpResponseRedirect('/index/')
    else :
        form = create_cat()

    return render(request, 'article/create_categorie.html', {'cat' : cat, 'form': form})

@login_required(login_url='index:login')
def user_article(request, user_id):
    cat = Categories.objects.all()[:5]
    art_user = Articles.objects.filter(writer=user_id)
    return render(request, "article/art_user.html", {'cat': cat, 'l_art': art_user})

@login_required
def edit(request, id_art=0):
    cat = Categories.objects.all()[:5]
    if id_art != 0:
        try :
            art = get_object_or_404(Articles, id=id_art)
        except Http404:
            return HttpResponseRedirect('/index/')
        usr = request.user
        
        if art.writer != usr.id:
            error(request, 'impossible de modifier cet article, vous n\'avez pas les droits')
            return HttpResponseRedirect('/article/read/%s/'% id_art)
        if request.method == 'POST':
            form = create_article(request.POST, 
                                  initial={'titre': art.title,
                                           'auteur': art.author,
                                           'date': art.date_pub,
                                           'texte':art.content,
                                           'categories': [art.categories_id],
                                          })
            if form.is_valid():
                art.title      = form.cleaned_data['titre']
                art.author     = form.cleaned_data['auteur']
                art.date_pub   = form.cleaned_data['date']
                content        = form.cleaned_data['hidden_content'] 
                art.content    = content
                cat_id         = form.cleaned_data['categories']
                art.categories_id = cat_id
                art.save()

                return HttpResponseRedirect('/article/read/%s/'% id_art)
        else:
            form = create_article(initial={'titre': art.title,
                                             'auteur': art.author,
                                             'date': art.date_pub,
                                             'texte':art.content,
                                             'cat': art.categories_id,
                                            })
    else :
        return HttpResponseRedirect('/index/')

    return render(request, "article/edit_article.html", {'cat': cat, 
                                                         'form': form,
                                                         'art': art,
                                                        })
@login_required
def create(request):
    cat = Categories.objects.all()[:5]
    if request.method == 'POST':
        form = create_article(request.POST)
        if form.is_valid():
            usr      = request.user
            auth     = form.cleaned_data['auteur']
            title    = form.cleaned_data['titre']
            date     = form.cleaned_data['date']
            categ_id = form.cleaned_data['categories']
            tmp_content  = form.cleaned_data['hidden_content'] 
            content = '<article>'+tmp_content+'</article>'
            art = Articles(title=title,
                           author=auth,
                           date_pub=date,
                           categories_id=categ_id,
                           content=content,
                           writer=usr.id)
            art.save()

            return HttpResponseRedirect('/article/read/%s/' % art.id)
    else:
        form = create_article()

    return render(request, 'article/create_article.html', {'cat': cat, 'form': form})

@login_required
def read(request, art_id, error="non"):

    cat = Categories.objects.all()[:5]
    art = Articles.objects.get(id=art_id)
    usr = User.objects.get(id=art.writer)
    return render(request, "article/read_art.html", {'art': art, 
                                                     'cat': cat, 
                                                     'writer': usr,
                                                    })

article/templates/article/art_user.html
{% extends 'index/base.html' %}
{% load static %}

{% block title %}Mes articles{% endblock %}

{% block content %}
  {% if l_art %}
    <ul>
    {% for art in l_art %}
      <li>
        <a href="{% url 'article:read' art.id %}">{{ art.title }}</a> 
        <em>({{ art.date_pub }})</em>
      </li>
    {% endfor %}
  {% else %}
    <p>vous n'avez aucun article pour le moment</p>
    <a href="{% url 'article:create' %}">creez en un ici</a>
  {% endif %}
{% endblock %}

article/templates/article/article_list.html
{% extends 'index/base.html' %}
{% load static %}

{%block title %} {{cat_name.cat}} {% endblock %}

{% block content %}
  {% if l_art %}
    {% for art in l_art %}
      <li>
          <div>
            <a href="{% url 'article:read' art.id %}">{{ art.title }}</a> 
            <em>{{art.author}} ({{art.date_pub }})</em>
          </div>
      </li>
    {% endfor %}
  {% else %}
    <p>Aucun article present dans cette categorie</p>
  {% endif %}
{% endblock %}

article/templates/article/categorie_list.html
{% extends 'index/base.html' %}

{% block title %}categories {% endblock %}

{% block content %}
  <p>Toutes les categories</p>
  <ul>
  {% for c in l_cat %}
    <li><a href="{% url 'article:categorie' c.id %}">{{ c.cat }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

article/templates/article/create_article.html
{% extends 'index/base.html' %}
{% load static %}

{% block title %}Ecrire un article{% endblock %}

{% block content %}
  <form action="{% url 'article:create' %}", method="POST">
    {% csrf_token %}

    {{ form.as_p}}
    <div class="well">
      <ul class="list-inline liste-unstyled">
        <li>
          <input type="button" value="g" style="font-weight:bold;" id="bouton_bold" onclick="cmd('bold');" class="btn btn-primary"/>
          <input type="button" value="i" style="font-style:italic;" id="bouton_it" onclick="cmd('italic');" class="btn btn-primary"/>
          <input type="button" value="s" style="text-decoration: underline;" id="bouton_und" onclick="cmd('underline');" class="btn btn-primary"/>
          <input type="button" value="text" style="text-decoration: line-through;" id="bouton_stri" onclick="cmd('strikethrough');" class="btn btn-primary"/>
        </li>
        <li>
          <div onclick="cmd('justifyright');" class="btn btn-primary" id="bouton-rig">
            <i class="fa fa-align-right" aria-hidden="true"></i>
          </div>
          <div onclick="cmd('justifycenter');" class="btn btn-primary">
            <i class="fa fa-align-center" aria-hidden="true"></i>
          </div>
          <div onclick="cmd('justifyleft');" class="btn btn-primary">
            <i class="fa fa-align-left" aria-hidden="true"></i>
          </div>
          <div onclick="cmd('justifyfull');" class="btn btn-primary">
            <i class="fa fa-align-justify" aria-hidden="true"></i>
          </div>
        </li>
        <li>
          <div onclick="cmd('insertunorderedlist');" class="btn btn-primary">
            <i class="fa fa-list-ul" aria-hidden="true"></i>
          </div>
          <div onclick="cmd('insertorderedlist');" class="btn btn-primary">
            <i class="fa fa-list-ol" aria-hidden="true"></i>
          </div>
        </li>
        <li>
          <input type="button" name="bouton_lien" value="lien" onclick="cmd('createLink');" class="btn btn-primary"/>
        </li>
        <li>
          <select class="form-control" onchange="cmd('heading', this.value);">
            <option value="">titre</option>
            <option value="h1">Titre 1</option>
            <option value="h2">Titre 2</option>
            <option value="h3">Titre 3</option>
          </select>
        </li>

      </ul>
      <div contenteditable="True" id="div_edit_art" class="form-control">
          article
      </div>
    </div>
    <input type="submit" class="btn btn-primary btn-md" value="editer l'article" onclick="result();">
  </form>
  <script type="text/javascript" src="{% static 'article/js/wysiwyg.js' %}"></script>
{% endblock %}

article/templates/article/create_categorie.html
{% extends 'index/base.html' %}
{% load static %}

{% block title %} creer une categorie{% endblock %}

{% block content %}
  <form  action="{% url 'article:create_cat' %}" method="POST">
    {% csrf_token %}

    {{form.as_p}}
    <input type="submit" class="btn btn-primary btn-md" value="creer la categorie">
  </form>
{% endblock %}

article/templates/article/edit_article.html
{% extends 'index/base.html' %}
{% load static %}

{% block title %}Ecrire un article{% endblock %}

{% block content %}
  <form action="{% url 'article:edit' art.id %}", method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <div class="well">
      <ul class="list-inline liste-unstyled">
        <li>
          <input type="button" value="g" style="font-weight:bold;" id="bouton_bold" onclick="cmd('Bold');" class="btn btn-primary"/>
          <input type="button" value="i" style="font-style:italic;" id="bouton_it" onclick="cmd('italic');" class="btn btn-primary"/>
          <input type="button" value="s" style="text-decoration: underline;" id="bouton_und" onclick="cmd('underline');" class="btn btn-primary"/>
          <input type="button" value="text" style="text-decoration: line-through;" id="bouton_stri" onclick="cmd('strikethrough');" class="btn btn-primary"/>
        </li>
        <li>
          <div onclick="cmd('justifyright');" class="btn btn-primary">
            <i class="fa fa-align-right" aria-hidden="true"></i>
          </div>
          <div onclick="cmd('justifycenter');" class="btn btn-primary">
            <i class="fa fa-align-center" aria-hidden="true"></i>
          </div>
          <div onclick="cmd('justifyleft');" class="btn btn-primary">
            <i class="fa fa-align-left" aria-hidden="true"></i>
          </div>
          <div onclick="cmd('justifyfull');" class="btn btn-primary">
            <i class="fa fa-align-justify" aria-hidden="true"></i>
          </div>
        </li>
        <li>
          <div onclick="cmd('insertunorderedlist');" class="btn btn-primary">
            <i class="fa fa-list-ul" aria-hidden="true"></i>
          </div>
          <div onclick="cmd('insertorderedlist');" class="btn btn-primary">
            <i class="fa fa-list-ol" aria-hidden="true"></i>
          </div>
        </li>
        <li>
          <input type="button" name="bouton_lien" value="lien" onclick="cmd('createLink');" class="btn btn-primary"/>
        </li>
        <li>
          <select class="form-control" onchange="cmd('heading', this.value);">
            <option value="">titre</option>
            <option value="h1">Titre 1</option>
            <option value="h2">Titre 2</option>
            <option value="h3">Titre 3</option>
          </select>
        </li>

      </ul>

      <div contenteditable="True" id="div_edit_art" class="form-control">
          {% autoescape off %}
          {{ art.content }}
          {% endautoescape %}
      </div>
    </div>
    <input type="submit" class="btn btn-primary btn-md" value="editer l'article" onclick="result();">
  </form>
  <script type="text/javascript" src="{% static 'article/js/wysiwyg.js' %}"></script>
{% endblock %}

article/templates/article/index.html
{% extends 'index/base.html' %}

{% block title %}articles {% endblock %}

{% block content %}
  {% if l_art %}
    <p>Tous les articles</p>
    <ul>
    {% for art in l_art %}
      <li><a href="{% url 'article:read' art.id %}">{{ art.title }}</a></li>
    {% endfor %}
    </ul>
  {% else %}
    <p>Aucun articles existant</p>
  {% endif %}
{% endblock %}

article/templates/article/read_art.html
{% extends 'index/base.html' %}
{%load static %}

{% block title %} {{art.title}}{% endblock %}

{% block content %}
  <div>
    <div>
      <div>
        {% for message in messages %}
          <div class="container">
            <div class="row">  
              <div class="col-lg-5">
                <div class="alert alert-warning">
                  <a class="close" data-dismiss="alert">×</a> 
                  <em>{{ message }}</em>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <p>
        <em>article posté le {{art.add_date}} par {{writer.username}}</em>
      </p>

      <h3> {{art.title}} </h3>

      {% if art.pub_date %}
        <p> 
          <em>publication originale le {{art.pub_date}}</em>
        </p>
      {% endif %}
    <div>
      <h4>mots clefs</h4>
        {% if art.keyword %}
          {{ art.keyword }}
        {% else %}
          <p><em>aucun mot clef pour cet article</em></p>
        {% endif %}
    </div>
    <div>
      <h4>abstract</h4>
        {% if art.abstract %}
          {{art.abstract}}
        {% else %}
          <p><em>aucun résumé</em></p>
        {% endif %}
    </div>
    <div id="summary">
      <h3>Sommaire</h3>
    </div>

    <div class="well">
      {% autoescape off %}
        {{ art.content }}
      {% endautoescape %}
    </div>
    <div>
      {{art.}}
    </div>

    <div>
      <a href="{% url 'article:edit' art.id %}">
        <button>modifier</button>
      </a>
    </div>
  </div>

  <script type="text/javascript" src="{% static 'article/js/tableOfContent.js' %}"></script>
{% endblock %}