article/urls.py
from django.conf.urls import url

from . import views

app_name = 'article'
urlpatterns = [
    #article/
    url(r'^$', views.article, name='article'),
    #article/categorie/[0-9]*
    url(r'^categorie/(?P<cat_id>[0-9]+)/', views.categorie, name="categorie"),
    #article/categorie/
    url(r'^categorie/', views.all_categorie, name="categorie_all"),
    #article/create_categorie/
    url(r'^create_categorie/', views.create_categorie, name="create_cat"),
    #article/edit/[0-9]*
    url(r'^edit/(?P<id_art>[0-9]*)/', views.edit, name="edit"),
    #article/edit/
    url(r'edit/', views.article),
    #article/edit/
    url(r'^create/', views.create, name="create"),
    #article/user_article/[0-9]*
    url(r'^user_article/(?P<user_id>[0-9]+)/', views.user_article, name="user_art"),
    #article/user_article/
    url(r'^user_article/', views.article),
    #article/read/[0-9]*/
    url(r'^read/(?P<art_id>[0-9]+)/', views.read, name='read'),
    #article/read/
    url(r'^read/', views.article)
]

index/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'index'
urlpatterns = [
    #index/
    url(r'^$', views.index, name='index'),
    #index/login/
    url(r'^login/$', auth_views.login, {'template_name': 'index/login.html'}, name="login"),
    #index/logout/
    url(r'^logout/$', auth_views.logout, {'next_page': '/index/'}, name="logout"),
    #index/register/
    url(r'^register/', views.create_user, name="registration"),
    #index/search/[A-Za-z0-9]*
    url(r'^search/', views.search, name="search"),
]

sciMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from index.views import index as art_index

urlpatterns = [
    url(r'^$', art_index),
    url(r'^index/', include('index.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^admin/', admin.site.urls),
]

index/templates/index/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      SciMS |{% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'index/libs/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'index/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'index/libs/fontAwesome/css/font-awesome.min.css' %}">
  </head>
    <body>

    <div class="container">
     
     <header class="page-header col-md-12">
        <div class="row">
           <h1><a href="{% url 'index:index' %}">SciMS</a></h1>  
        </div>
        <div class="row">
          <div class="col-md-8">
            {% if cat %}
              {% for c in cat %}
                <a href="{%url 'article:categorie' c.id %}">
                  <button class="btn btn-primary btn-md">
                    {{c.cat}}
                  </button>
                </a>
              {% endfor %}
            {% endif %}
            <a href="{% url 'article:categorie_all' %}">
              <button class="btn btn-primary btn-md">
                toutes les categories
              </button>
            </a>
          </div>
          <form class="input-group col-md-4" action="{% url 'index:search' %}" method="POST">
          {% csrf_token %}
            <input type="text" class="form-control"  name="str_srch" placeholder="Search"/>

            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
            </div>
          </form>
        </div>
      </header>

      <div class="row">
        {% block nav %}
          <nav class = "navbar navbar-nav col-md-3">
            <ul class="nav nav-pills nav-stacked">
              {% if user.is_authenticated %} 
              <li class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                  <i class="fa fa-user-circle fa-md"></i> {{user.username}}
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item" href="{% url 'index:logout' %}"><i class="fa fa-sign-out fa-md"></i> se deconnecter</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'article:create' %}"><i class="fa fa-pencil-square fa-md"></i> Créer un article</a>
                  </li>
                  {% if user.is_superuser %}
                    <li>
                      <a class="dropdown-item" href="{% url 'article:create_cat' %}"><i class="fa fa-pencil-square fa-md"></i> Creer une categorie</a>
                    </li>
                  {% endif %}
                  <li>
                    <a class="dropdown-item" href="{% url 'article:user_art' user.id %}"><i class="fa fa-folder fa-md"></i> mes articles</a>
                  </li>
                </ul>
              </li>
              {% else %}
                <li class="menu">
                  <a href="{% url 'index:login' %}"><i class="fa fa-sign-in fa-md"></i> se connecter</a>
                </li>
                <li>
                  <a href="{% url 'index:registration' %}"><i class="fa fa-user-plus fa-md"></i> S'inscrire</a>
                </li>
              {% endif %}
            </ul>
          </nav>
       
        {% endblock %}
        <div class="col-md-9">
            
            {% block auth %}
            {% endblock %}

            {% block content %}
            {% endblock %}
        
        </div>
      </div>  
      <hr/>
      <footer class="col-md-12">
        <p>copyright : sciMS team</p>
        <p>contact : <a href="mailto:florian.souday@etu.univ-rouen.fr">florian.souday@etu.univ-rouen.fr</a><br/>
        contact : <a href="mailto:tristan.rodriguez@etu.univ-rouen.fr">tristan.rodriguez@etu.univ-rouen.fr</a>
      </p>
      </footer>
    </div>

    <script type="text/javascript" src="{% static 'index/libs/jquery/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'index/libs/bootstrap/js/bootstrap.min.js' %}"></script>
    
  </body>
</html>

index/templates/index/index.html
{% extends "index/base.html" %}
{% load static %}

{% block title %} Home {% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-5">
      <p>derniers articles ajoutés</p>
      <ul>
        {% for art in l_art %}
          <li><a href="{% url 'article:read' art.id %}">{{art.title}}</a></li>
        {% endfor %}
        <a href= "{% url 'article:article' %}"> 
              <button class="btn btn-primary btn-md">
                Tous les articles
              </button>
            </a>
      </ul>
    </div>
    <div class="col-lg-5">
      <p>dernières catégories ajoutées</p>
      <ul>
        {% for cat in l_cat %}
          <li><a href="{% url 'article:categorie' cat.id %}">{{ cat.cat }}</a></li>
        {% endfor %}
      <a href= "{% url 'article:categorie_all' %}"> 
              <button class="btn btn-primary btn-md">
                Toutes les categories
              </button>
            </a>
      </ul>
    </div>
  </div>
{% endblock %}

index/templates/index/login.html
{% extends "index/base.html" %}

{% block title %} Connection {% endblock %}

{% block auth %}  
  <form action="{% url 'index:login' %}" method="post" class='form-inline'>
    {% csrf_token %}
    <div class='form-group'>
      <label for='usrname'>username</label>
      <input type="text" name="username" class='form-control' id='usrname' placeholder="Username" />
    </div>
    <div class='form-group'>
      <label for='passwd'>password</label>
      <input type="password" name="password" class='form-control' id='passwd' placeholder="password" />
    </div>
    <input type="submit" class='btn btn-primary btn-md' value="connexion">
  </form>
{% endblock %}

index/templates/index/registration.html
{% extends 'index/base.html' %}

{% block title %} Inscription {% endblock %}

{% block content %}
  <div>
    {% for message in messages %}
      <div class="container">
        <div class="row">  
          <div class="col-lg-5">
            <div class="alert alert-warning">
              <a class="close" data-dismiss="alert">×</a> 
              <em>{{ message }}</em>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  
  <form action="{% url 'index:registration' %}" method="post">
    <div class="form-group">
      {% csrf_token %}
      {{ form.as_p }}
    </div>
    <input type="submit" value="s'inscrire" class="btn btn-primary btn-md"/>
  </form>
{% endblock %}

index/templates/index/search.html
{% extends 'index/base.html' %}

{% block title %} {{str_src}} {% endblock %}

{% block content %}
  <div>
    <h3>
      resultat de la recherche <em>{{str_src}}</em>
    </h3>
    <div class="row">
      <div class="col-lg-5">
        <h4>Categories</h4>
        {% if l_cat %}
          <ul>
            {% for r_cat in l_cat %}
              <li>
                <a href="{% url 'article:categorie' r_cat.id %}">{{r_cat.cat}}</a>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>Aucunes catégories trouvée</p>
        {% endif %}
      </div>
      <div class="col-lg-5">
        <h4>Articles</h4>
        {% if l_art %}
          <ul>
          {% for r_art in l_art %}
            <li>
              <a href="{% url 'article:read' r_art.id %}">{{ r_art.title }}</a>
            </li>
          {% endfor %}
          </ul>
        {% else %}
          <p> Aucuns Articles trouvé</p>
        {% endif %}
      </div>
    </div>

    <div col="row">
      <h4>Utilisateurs</h4>
      {% if l_usr %}
        {% for r_usr in l_usr %}
          <li>
            <a href="{% url 'article:user_art' r_usr.id %}">{{r_usr.username}}</a>
          </li>
        {% endfor %}

      {% else %}
        <p>Aucuns utilisateurs trouvé</p>
      {% endif %}
    </div>
  </div>

{% endblock %}